server:
  port: 8080
spring:
  application:
    name: service-prueba-notas
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:universidad
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev